defmodule FakeArtist.Game.Lists do
  def words() do
    [
      %{ category: "accessory", text: "bandana" },
      %{ category: "accessory", text: "earring" },
      %{ category: "accessory", text: "eyepatch" },
      %{ category: "accessory", text: "hairtie" },
      %{ category: "accessory", text: "handbag" },
      %{ category: "accessory", text: "handkerchief" },
      %{ category: "accessory", text: "headband" },
      %{ category: "accessory", text: "kneepads" },
      %{ category: "accessory", text: "necklace" },
      %{ category: "accessory", text: "nosering" },
      %{ category: "accessory", text: "partyhat" },
      %{ category: "accessory", text: "shoelace" },
      %{ category: "accessory", text: "umbrella" },
      %{ category: "anatomy", text: "backbone" },
      %{ category: "anatomy", text: "eyeball" },
      %{ category: "anatomy", text: "eyebrow" },
      %{ category: "anatomy", text: "eyelash" },
      %{ category: "anatomy", text: "forehead" },
      %{ category: "anatomy", text: "kneecap" },
      %{ category: "anatomy", text: "knuckle" },
      %{ category: "anatomy", text: "mustache" },
      %{ category: "anatomy", text: "nosehair" },
      %{ category: "anatomy", text: "shoulder" },
      %{ category: "anatomy", text: "skeleton" },
      %{ category: "anatomy", text: "stomach" },
      %{ category: "anatomy", text: "tentacle" },
      %{ category: "anatomy", text: "unibrow" },
      %{ category: "anatomy", text: "whiskers" },
      %{ category: "animal", text: "aardvark" },
      %{ category: "animal", text: "alpaca" },
      %{ category: "animal", text: "ant" },
      %{ category: "animal", text: "anteater" },
      %{ category: "animal", text: "armadillo" },
      %{ category: "animal", text: "baboon" },
      %{ category: "animal", text: "badger" },
      %{ category: "animal", text: "bat" },
      %{ category: "animal", text: "bear" },
      %{ category: "animal", text: "beaver" },
      %{ category: "animal", text: "bee" },
      %{ category: "animal", text: "bird" },
      %{ category: "animal", text: "buffalo" },
      %{ category: "animal", text: "bull" },
      %{ category: "animal", text: "calf" },
      %{ category: "animal", text: "camel" },
      %{ category: "animal", text: "cat" },
      %{ category: "animal", text: "caterpillar" },
      %{ category: "animal", text: "catfish" },
      %{ category: "animal", text: "chameleon" },
      %{ category: "animal", text: "cheetah" },
      %{ category: "animal", text: "chicken" },
      %{ category: "animal", text: "chihuahua " },
      %{ category: "animal", text: "chimpanzee" },
      %{ category: "animal", text: "cicada " },
      %{ category: "animal", text: "cockroach" },
      %{ category: "animal", text: "cow" },
      %{ category: "animal", text: "crab" },
      %{ category: "animal", text: "crane" },
      %{ category: "animal", text: "cricket" },
      %{ category: "animal", text: "crocodile" },
      %{ category: "animal", text: "deer" },
      %{ category: "animal", text: "dinosaur" },
      %{ category: "animal", text: "dog" },
      %{ category: "animal", text: "dolphin" },
      %{ category: "animal", text: "donkey" },
      %{ category: "animal", text: "dragonfly" },
      %{ category: "animal", text: "duck" },
      %{ category: "animal", text: "eagle" },
      %{ category: "animal", text: "elephant" },
      %{ category: "animal", text: "firefly" },
      %{ category: "animal", text: "fish" },
      %{ category: "animal", text: "flamingo" },
      %{ category: "animal", text: "fly" },
      %{ category: "animal", text: "fox" },
      %{ category: "animal", text: "frog" },
      %{ category: "animal", text: "giraffe" },
      %{ category: "animal", text: "goat" },
      %{ category: "animal", text: "goldfish" },
      %{ category: "animal", text: "goose" },
      %{ category: "animal", text: "gorilla" },
      %{ category: "animal", text: "grasshopper" },
      %{ category: "animal", text: "hamster" },
      %{ category: "animal", text: "hippopotamus" },
      %{ category: "animal", text: "horse" },
      %{ category: "animal", text: "hyena" },
      %{ category: "animal", text: "jaguar" },
      %{ category: "animal", text: "kangaroo" },
      %{ category: "animal", text: "kitten" },
      %{ category: "animal", text: "ladybug" },
      %{ category: "animal", text: "leopard" },
      %{ category: "animal", text: "lion" },
      %{ category: "animal", text: "lizard" },
      %{ category: "animal", text: "llama" },
      %{ category: "animal", text: "lobster" },
      %{ category: "animal", text: "mammoth" },
      %{ category: "animal", text: "monkey" },
      %{ category: "animal", text: "moose" },
      %{ category: "animal", text: "mosquito" },
      %{ category: "animal", text: "mouse" },
      %{ category: "animal", text: "narwhal" },
      %{ category: "animal", text: "octopus" },
      %{ category: "animal", text: "ostrich" },
      %{ category: "animal", text: "otter" },
      %{ category: "animal", text: "owl" },
      %{ category: "animal", text: "oyster" },
      %{ category: "animal", text: "panda" },
      %{ category: "animal", text: "pangolin" },
      %{ category: "animal", text: "panther" },
      %{ category: "animal", text: "parrot" },
      %{ category: "animal", text: "peacock" },
      %{ category: "animal", text: "pelican" },
      %{ category: "animal", text: "penguin" },
      %{ category: "animal", text: "pig" },
      %{ category: "animal", text: "pigeon" },
      %{ category: "animal", text: "pitbull" },
      %{ category: "animal", text: "platypus" },
      %{ category: "animal", text: "poodle" },
      %{ category: "animal", text: "porcupine" },
      %{ category: "animal", text: "puppy" },
      %{ category: "animal", text: "rabbit" },
      %{ category: "animal", text: "raccoon" },
      %{ category: "animal", text: "rat" },
      %{ category: "animal", text: "reindeer" },
      %{ category: "animal", text: "reptile" },
      %{ category: "animal", text: "rhinoceros" },
      %{ category: "animal", text: "rooster" },
      %{ category: "animal", text: "scorpion" },
      %{ category: "animal", text: "seagull" },
      %{ category: "animal", text: "seahorse" },
      %{ category: "animal", text: "seal" },
      %{ category: "animal", text: "shark" },
      %{ category: "animal", text: "sheep" },
      %{ category: "animal", text: "shrimp" },
      %{ category: "animal", text: "skunk" },
      %{ category: "animal", text: "snail" },
      %{ category: "animal", text: "snake" },
      %{ category: "animal", text: "spider" },
      %{ category: "animal", text: "squid" },
      %{ category: "animal", text: "squirrel" },
      %{ category: "animal", text: "starfish" },
      %{ category: "animal", text: "stork" },
      %{ category: "animal", text: "swan" },
      %{ category: "animal", text: "tadpole" },
      %{ category: "animal", text: "tiger" },
      %{ category: "animal", text: "toad" },
      %{ category: "animal", text: "tortoise" },
      %{ category: "animal", text: "tropical fish" },
      %{ category: "animal", text: "tuna" },
      %{ category: "animal", text: "turkey" },
      %{ category: "animal", text: "turtle" },
      %{ category: "animal", text: "vulture" },
      %{ category: "animal", text: "walrus" },
      %{ category: "animal", text: "whale" },
      %{ category: "animal", text: "wolf" },
      %{ category: "animal", text: "wombat" },
      %{ category: "animal", text: "worm" },
      %{ category: "animal", text: "zebra" },
      %{ category: "clothing", text: "bandana" },
      %{ category: "clothing", text: "belt" },
      %{ category: "clothing", text: "bikini" },
      %{ category: "clothing", text: "boots" },
      %{ category: "clothing", text: "bowtie" },
      %{ category: "clothing", text: "cap" },
      %{ category: "clothing", text: "chasity belt" },
      %{ category: "clothing", text: "coat" },
      %{ category: "clothing", text: "cowboy hat" },
      %{ category: "clothing", text: "dress" },
      %{ category: "clothing", text: "earmuffs" },
      %{ category: "clothing", text: "eyepatch" },
      %{ category: "clothing", text: "glasses" },
      %{ category: "clothing", text: "gloves" },
      %{ category: "clothing", text: "hairtie" },
      %{ category: "clothing", text: "hat" },
      %{ category: "clothing", text: "headband" },
      %{ category: "clothing", text: "hoodie" },
      %{ category: "clothing", text: "jacket" },
      %{ category: "clothing", text: "jeans" },
      %{ category: "clothing", text: "kneepads" },
      %{ category: "clothing", text: "mittens" },
      %{ category: "clothing", text: "necklace" },
      %{ category: "clothing", text: "overalls" },
      %{ category: "clothing", text: "pajamas" },
      %{ category: "clothing", text: "pantsuit" },
      %{ category: "clothing", text: "partyhat" },
      %{ category: "clothing", text: "raincoat" },
      %{ category: "clothing", text: "sandals" },
      %{ category: "clothing", text: "scarf" },
      %{ category: "clothing", text: "shirt" },
      %{ category: "clothing", text: "shoes" },
      %{ category: "clothing", text: "skirt" },
      %{ category: "clothing", text: "slippers" },
      %{ category: "clothing", text: "sneakers" },
      %{ category: "clothing", text: "socks" },
      %{ category: "clothing", text: "sombrero" },
      %{ category: "clothing", text: "stockings" },
      %{ category: "clothing", text: "suit" },
      %{ category: "clothing", text: "sweater" },
      %{ category: "clothing", text: "sweatshirt" },
      %{ category: "clothing", text: "swimsuit" },
      %{ category: "clothing", text: "t-shirt" },
      %{ category: "clothing", text: "tie" },
      %{ category: "clothing", text: "tophat" },
      %{ category: "clothing", text: "trousers" },
      %{ category: "clothing", text: "underpants" },
      %{ category: "clothing ", text: "tophat" },
      %{ category: "computing", text: "computer" },
      %{ category: "computing", text: "facebook" },
      %{ category: "computing", text: "firewall" },
      %{ category: "computing", text: "hashtag" },
      %{ category: "computing", text: "keyboard" },
      %{ category: "computing", text: "macbook" },
      %{ category: "computing", text: "password" },
      %{ category: "computing", text: "twitter" },
      %{ category: "fairytale", text: "aladdin" },
      %{ category: "fairytale", text: "ali baba and the forty thieves" },
      %{ category: "fairytale", text: "beauty and the beast" },
      %{ category: "fairytale", text: "cinderella" },
      %{ category: "fairytale", text: "goldilocks and the three bears" },
      %{ category: "fairytale", text: "hansel and gretel" },
      %{ category: "fairytale", text: "puss in boots" },
      %{ category: "fairytale", text: "rapunzel" },
      %{ category: "fairytale", text: "rumpelstiltskin" },
      %{ category: "fairytale", text: "sinbad" },
      %{ category: "fairytale", text: "sleeping beauty" },
      %{ category: "fairytale", text: "snow white" },
      %{ category: "fairytale", text: "the emperor's new clothes" },
      %{ category: "fairytale", text: "the fisherman and the jinni" },
      %{ category: "fairytale", text: "the frog prince" },
      %{ category: "fairytale", text: "the golden fish" },
      %{ category: "fairytale", text: "the golden goose" },
      %{ category: "fairytale", text: "the little mermaid" },
      %{ category: "fairytale", text: "the princess and the pea" },
      %{ category: "fairytale", text: "the steadfast tin soldier" },
      %{ category: "fairytale", text: "the three little pigs" },
      %{ category: "fairytale", text: "the tin soldier" },
      %{ category: "fairytale", text: "the tinderbox" },
      %{ category: "fairytale", text: "the ugly duckling" },
      %{ category: "fairytale", text: "thumbelina" },
      %{ category: "fairytale", text: "thumbelina" },
      %{ category: "fairytale", text: "thumbelina" },
      %{ category: "family", text: "aunt" },
      %{ category: "family", text: "brother" },
      %{ category: "family", text: "children" },
      %{ category: "family", text: "cousin" },
      %{ category: "family", text: "father" },
      %{ category: "family", text: "father in law" },
      %{ category: "family", text: "god father" },
      %{ category: "family", text: "god mother" },
      %{ category: "family", text: "granddaugther" },
      %{ category: "family", text: "grandma" },
      %{ category: "family", text: "grandpa" },
      %{ category: "family", text: "grandson" },
      %{ category: "family", text: "husband" },
      %{ category: "family", text: "mother" },
      %{ category: "family", text: "mother in law" },
      %{ category: "family", text: "nephew" },
      %{ category: "family", text: "niece" },
      %{ category: "family", text: "parents" },
      %{ category: "family", text: "sister" },
      %{ category: "family", text: "step brother" },
      %{ category: "family", text: "step father" },
      %{ category: "family", text: "step mother" },
      %{ category: "family", text: "step sister" },
      %{ category: "family", text: "uncle" },
      %{ category: "family", text: "wife" },
      %{ category: "famous landmark", text: "acropolis" },
      %{ category: "famous landmark", text: "big ben" },
      %{ category: "famous landmark", text: "brandenburg gate" },
      %{ category: "famous landmark", text: "capitol hill" },
      %{ category: "famous landmark", text: "christ the redeemer statue" },
      %{ category: "famous landmark", text: "colosseum" },
      %{ category: "famous landmark", text: "easter island" },
      %{ category: "famous landmark", text: "empire state building" },
      %{ category: "famous landmark", text: "fontana de trevi" },
      %{ category: "famous landmark", text: "golden gate bridge " },
      %{ category: "famous landmark", text: "grand canyon" },
      %{ category: "famous landmark", text: "leaning tower of pisa" },
      %{ category: "famous landmark", text: "loch ness" },
      %{ category: "famous landmark", text: "mount rushmore" },
      %{ category: "famous landmark", text: "niagra falls" },
      %{ category: "famous landmark", text: "statue of liberty" },
      %{ category: "famous landmark", text: "stonehenge" },
      %{ category: "famous landmark", text: "sydney opera house" },
      %{ category: "famous landmark", text: "the eiffel tower" },
      %{ category: "famous landmark", text: "the forbidden city" },
      %{ category: "famous landmark", text: "the great chinese wall" },
      %{ category: "famous landmark", text: "the hollywood sign " },
      %{ category: "famous landmark", text: "the kremlin" },
      %{ category: "famous landmark", text: "the little mermaid" },
      %{ category: "famous landmark", text: "the louvre " },
      %{ category: "famous landmark", text: "the pyramids" },
      %{ category: "famous landmark", text: "the sphinx" },
      %{ category: "famous landmark", text: "the taj mahal" },
      %{ category: "famous person", text: "angelina jolie" },
      %{ category: "famous person", text: "beckham" },
      %{ category: "famous person", text: "bob dylan" },
      %{ category: "famous person", text: "brad pitt" },
      %{ category: "famous person", text: "bruce lee" },
      %{ category: "famous person", text: "colbert" },
      %{ category: "famous person", text: "donald trump" },
      %{ category: "famous person", text: "eminem" },
      %{ category: "famous person", text: "gandhi" },
      %{ category: "famous person", text: "geronimo" },
      %{ category: "famous person", text: "greenday" },
      %{ category: "famous person", text: "jay leno" },
      %{ category: "famous person", text: "justin bieber" },
      %{ category: "famous person", text: "kate moss" },
      %{ category: "famous person", text: "lady gaga" },
      %{ category: "famous person", text: "lil wayne" },
      %{ category: "famous person", text: "lincoln" },
      %{ category: "famous person", text: "ludacris" },
      %{ category: "famous person", text: "madonna" },
      %{ category: "famous person", text: "mc hammer" },
      %{ category: "famous person", text: "picasso" },
      %{ category: "famous person", text: "pitbull" },
      %{ category: "famous person", text: "rihanna" },
      %{ category: "famous person", text: "tom hanks" },
      %{ category: "famous person", text: "van gogh" },
      %{ category: "famous person", text: "vincent van gogh" },
      %{ category: "festivity", text: "bar mitzvah" },
      %{ category: "festivity", text: "birthday" },
      %{ category: "festivity", text: "black friday" },
      %{ category: "festivity", text: "christmas" },
      %{ category: "festivity", text: "columbus day" },
      %{ category: "festivity", text: "divali" },
      %{ category: "festivity", text: "día de muertos" },
      %{ category: "festivity", text: "easter" },
      %{ category: "festivity", text: "election" },
      %{ category: "festivity", text: "festivus" },
      %{ category: "festivity", text: "graduation" },
      %{ category: "festivity", text: "groundhog day" },
      %{ category: "festivity", text: "halloween" },
      %{ category: "festivity", text: "hanukkah" },
      %{ category: "festivity", text: "independence day" },
      %{ category: "festivity", text: "kwanzaa" },
      %{ category: "festivity", text: "mother`s day" },
      %{ category: "festivity", text: "new year`s eve" },
      %{ category: "festivity", text: "octoberfest" },
      %{ category: "festivity", text: "passover" },
      %{ category: "festivity", text: "ramadan" },
      %{ category: "festivity", text: "st. patrick`s day" },
      %{ category: "festivity", text: "thanks giving" },
      %{ category: "festivity", text: "valentine`s day" },
      %{ category: "festivity", text: "wedding" },
      %{ category: "film genres", text: "action" },
      %{ category: "film genres", text: "animation" },
      %{ category: "film genres", text: "comedy" },
      %{ category: "film genres", text: "disasters" },
      %{ category: "film genres", text: "documentry" },
      %{ category: "film genres", text: "gangster" },
      %{ category: "film genres", text: "horror" },
      %{ category: "film genres", text: "mockumentry" },
      %{ category: "film genres", text: "musical" },
      %{ category: "film genres", text: "rom-com" },
      %{ category: "film genres", text: "sci-fi" },
      %{ category: "film genres", text: "slapstick" },
      %{ category: "film genres", text: "sport" },
      %{ category: "film genres", text: "thriller" },
      %{ category: "film genres", text: "war" },
      %{ category: "film genres", text: "western" },
      %{ category: "film genres", text: "zombies" },
      %{ category: "food", text: "bacon" },
      %{ category: "food", text: "baguette" },
      %{ category: "food", text: "barbeque" },
      %{ category: "food", text: "beans" },
      %{ category: "food", text: "beer" },
      %{ category: "food", text: "burrito" },
      %{ category: "food", text: "cake" },
      %{ category: "food", text: "cereal" },
      %{ category: "food", text: "champagne" },
      %{ category: "food", text: "cheese" },
      %{ category: "food", text: "chicken wings" },
      %{ category: "food", text: "coffee" },
      %{ category: "food", text: "corndog" },
      %{ category: "food", text: "croissant" },
      %{ category: "food", text: "cupcake" },
      %{ category: "food", text: "eggroll" },
      %{ category: "food", text: "espresso" },
      %{ category: "food", text: "fast food" },
      %{ category: "food", text: "fish and chips" },
      %{ category: "food", text: "frosting" },
      %{ category: "food", text: "hambone" },
      %{ category: "food", text: "hamburger" },
      %{ category: "food", text: "hamwich" },
      %{ category: "food", text: "hot sauce" },
      %{ category: "food", text: "junk food" },
      %{ category: "food", text: "kebab" },
      %{ category: "food", text: "ketchup" },
      %{ category: "food", text: "lasagna" },
      %{ category: "food", text: "lemonade" },
      %{ category: "food", text: "macaroni" },
      %{ category: "food", text: "martini" },
      %{ category: "food", text: "mashed potatoes" },
      %{ category: "food", text: "meatballs" },
      %{ category: "food", text: "milk" },
      %{ category: "food", text: "mushroom" },
      %{ category: "food", text: "mustard" },
      %{ category: "food", text: "noodles" },
      %{ category: "food", text: "oatmeal" },
      %{ category: "food", text: "pancake" },
      %{ category: "food", text: "pasta" },
      %{ category: "food", text: "pie" },
      %{ category: "food", text: "pizza" },
      %{ category: "food", text: "popcorn" },
      %{ category: "food", text: "pretzel" },
      %{ category: "food", text: "pumpkin" },
      %{ category: "food", text: "salad" },
      %{ category: "food", text: "sandwich" },
      %{ category: "food", text: "sausage" },
      %{ category: "food", text: "seafood" },
      %{ category: "food", text: "smoothie" },
      %{ category: "food", text: "snowcone" },
      %{ category: "food", text: "soy sauce" },
      %{ category: "food", text: "sushi" },
      %{ category: "food", text: "tea" },
      %{ category: "food", text: "tequila" },
      %{ category: "food", text: "waffles" },
      %{ category: "food", text: "whiskey" },
      %{ category: "furniture", text: "barstool" },
      %{ category: "furniture", text: "bathtub" },
      %{ category: "furniture", text: "bed" },
      %{ category: "furniture", text: "bookcase" },
      %{ category: "furniture", text: "bunkbed" },
      %{ category: "furniture", text: "cabinet" },
      %{ category: "furniture", text: "chair" },
      %{ category: "furniture", text: "dresser" },
      %{ category: "furniture", text: "waterbed" },
      %{ category: "games", text: "balloon" },
      %{ category: "games", text: "checkers" },
      %{ category: "games", text: "dreidel" },
      %{ category: "games", text: "gameboy" },
      %{ category: "games", text: "hulahoop" },
      %{ category: "games", text: "joystick" },
      %{ category: "games", text: "monopoly" },
      %{ category: "games", text: "pinball" },
      %{ category: "games", text: "pinwheel" },
      %{ category: "games", text: "scrabble" },
      %{ category: "games", text: "swingset" },
      %{ category: "games", text: "yahtzee" },
      %{ category: "geography", text: "america" },
      %{ category: "geography", text: "atlanta" },
      %{ category: "geography", text: "bahamas" },
      %{ category: "geography", text: "england" },
      %{ category: "geography", text: "finland" },
      %{ category: "geography", text: "florida" },
      %{ category: "geography", text: "germany" },
      %{ category: "geography", text: "holland" },
      %{ category: "geography", text: "hongkong" },
      %{ category: "geography", text: "ireland" },
      %{ category: "geography", text: "jamaica" },
      %{ category: "geography", text: "new-york" },
      %{ category: "geography", text: "orlando" },
      %{ category: "geography", text: "scotland" },
      %{ category: "location", text: "airport" },
      %{ category: "location", text: "apartment building" },
      %{ category: "location", text: "bank" },
      %{ category: "location", text: "bar" },
      %{ category: "location", text: "barber shop" },
      %{ category: "location", text: "barn" },
      %{ category: "location", text: "beach" },
      %{ category: "location", text: "book store" },
      %{ category: "location", text: "bowling alley" },
      %{ category: "location", text: "bus stop" },
      %{ category: "location", text: "casino" },
      %{ category: "location", text: "castle" },
      %{ category: "location", text: "cathedral" },
      %{ category: "location", text: "cemetery" },
      %{ category: "location", text: "church" },
      %{ category: "location", text: "circus" },
      %{ category: "location", text: "convenience store" },
      %{ category: "location", text: "courthouse" },
      %{ category: "location", text: "department store" },
      %{ category: "location", text: "desert" },
      %{ category: "location", text: "disco" },
      %{ category: "location", text: "dungeon" },
      %{ category: "location", text: "fire station" },
      %{ category: "location", text: "garden" },
      %{ category: "location", text: "gas station" },
      %{ category: "location", text: "golf course" },
      %{ category: "location", text: "hospital" },
      %{ category: "location", text: "house" },
      %{ category: "location", text: "library" },
      %{ category: "location", text: "lighthouse" },
      %{ category: "location", text: "mall" },
      %{ category: "location", text: "mansion" },
      %{ category: "location", text: "movie theater" },
      %{ category: "location", text: "museum" },
      %{ category: "location", text: "office building" },
      %{ category: "location", text: "opera house" },
      %{ category: "location", text: "orchard" },
      %{ category: "location", text: "palace" },
      %{ category: "location", text: "petshop" },
      %{ category: "location", text: "police station" },
      %{ category: "location", text: "post office" },
      %{ category: "location", text: "prison" },
      %{ category: "location", text: "pub" },
      %{ category: "location", text: "restaurant" },
      %{ category: "location", text: "safari" },
      %{ category: "location", text: "saw mill" },
      %{ category: "location", text: "school" },
      %{ category: "location", text: "skyscraper" },
      %{ category: "location", text: "supermarket" },
      %{ category: "location", text: "swimming pool" },
      %{ category: "location", text: "temple" },
      %{ category: "location", text: "theater" },
      %{ category: "location", text: "theme park" },
      %{ category: "location", text: "train station" },
      %{ category: "location", text: "vet clinic" },
      %{ category: "location", text: "zoo" },
      %{ category: "medical", text: "crutches" },
      %{ category: "medical", text: "dandruff" },
      %{ category: "medical", text: "dentures" },
      %{ category: "medical", text: "firstaid" },
      %{ category: "medical", text: "headache" },
      %{ category: "medical", text: "hospital" },
      %{ category: "medical", text: "insomnia" },
      %{ category: "medical", text: "medicine" },
      %{ category: "medical", text: "papercut" },
      %{ category: "medical", text: "seasick" },
      %{ category: "medical", text: "sunburn" },
      %{ category: "medical", text: "vaccine" },
      %{ category: "medical", text: "vitamin" },
      %{ category: "movies", text: "a clockwork orange" },
      %{ category: "movies", text: "alien" },
      %{ category: "movies", text: "armagedon" },
      %{ category: "movies", text: "austin powers" },
      %{ category: "movies", text: "avengers" },
      %{ category: "movies", text: "back to the future" },
      %{ category: "movies", text: "beetlejuice" },
      %{ category: "movies", text: "braveheart" },
      %{ category: "movies", text: "die hard" },
      %{ category: "movies", text: "e.t." },
      %{ category: "movies", text: "fargo" },
      %{ category: "movies", text: "finding nemo" },
      %{ category: "movies", text: "forrest gump" },
      %{ category: "movies", text: "frozen" },
      %{ category: "movies", text: "gladiator" },
      %{ category: "movies", text: "golden eye" },
      %{ category: "movies", text: "gone with the wind" },
      %{ category: "movies", text: "groundhog day" },
      %{ category: "movies", text: "home alone" },
      %{ category: "movies", text: "inception" },
      %{ category: "movies", text: "indiana jones" },
      %{ category: "movies", text: "inglourious basterds" },
      %{ category: "movies", text: "jaws" },
      %{ category: "movies", text: "jurassic park" },
      %{ category: "movies", text: "king kong" },
      %{ category: "movies", text: "lion king" },
      %{ category: "movies", text: "mary poppins" },
      %{ category: "movies", text: "minority report" },
      %{ category: "movies", text: "mission impossible" },
      %{ category: "movies", text: "monty python and the holy grail" },
      %{ category: "movies", text: "princess bride" },
      %{ category: "movies", text: "pulp fiction" },
      %{ category: "movies", text: "robocop" },
      %{ category: "movies", text: "rocky" },
      %{ category: "movies", text: "rocky horror picture show" },
      %{ category: "movies", text: "saving private ryan" },
      %{ category: "movies", text: "scarface" },
      %{ category: "movies", text: "shrek" },
      %{ category: "movies", text: "star wars" },
      %{ category: "movies", text: "terminator" },
      %{ category: "movies", text: "the good, the bad and the ugly" },
      %{ category: "movies", text: "the green mile" },
      %{ category: "movies", text: "the lord of the rings" },
      %{ category: "movies", text: "the matrix" },
      %{ category: "movies", text: "the shawshank redemption" },
      %{ category: "movies", text: "the social network" },
      %{ category: "movies", text: "the wizard of oz" },
      %{ category: "movies", text: "titanic" },
      %{ category: "movies", text: "toy story" },
      %{ category: "movies", text: "west side story" },
      %{ category: "movies", text: "wonder woman" },
      %{ category: "movies", text: "x-men" },
      %{ category: "music band", text: "ac/dc" },
      %{ category: "music band", text: "adele" },
      %{ category: "music band", text: "beatles" },
      %{ category: "music band", text: "beyonce" },
      %{ category: "music band", text: "billie eilish" },
      %{ category: "music band", text: "bon jovi" },
      %{ category: "music band", text: "bruno mars" },
      %{ category: "music band", text: "childish gambino" },
      %{ category: "music band", text: "coldplay" },
      %{ category: "music band", text: "daftpunk" },
      %{ category: "music band", text: "david bowie" },
      %{ category: "music band", text: "dr. dre" },
      %{ category: "music band", text: "drake" },
      %{ category: "music band", text: "ed shiran" },
      %{ category: "music band", text: "elton john" },
      %{ category: "music band", text: "eminem" },
      %{ category: "music band", text: "guns and roses" },
      %{ category: "music band", text: "jay z" },
      %{ category: "music band", text: "justin bieber" },
      %{ category: "music band", text: "justin timberlake" },
      %{ category: "music band", text: "kanye west" },
      %{ category: "music band", text: "katy perry" },
      %{ category: "music band", text: "lady gaga" },
      %{ category: "music band", text: "led zeppelin" },
      %{ category: "music band", text: "mariah carey" },
      %{ category: "music band", text: "michael jackson" },
      %{ category: "music band", text: "muse" },
      %{ category: "music band", text: "nicki minaj" },
      %{ category: "music band", text: "nirvana" },
      %{ category: "music band", text: "pink floyd" },
      %{ category: "music band", text: "pitbull" },
      %{ category: "music band", text: "prince" },
      %{ category: "music band", text: "queen" },
      %{ category: "music band", text: "rihana" },
      %{ category: "music band", text: "skrillex" },
      %{ category: "music band", text: "snoop dogg" },
      %{ category: "music band", text: "taylor swift" },
      %{ category: "music band", text: "the black eyed peas" },
      %{ category: "music band", text: "tupac shakur" },
      %{ category: "music band", text: "u2" },
      %{ category: "music genre", text: "blues" },
      %{ category: "music genre", text: "classical" },
      %{ category: "music genre", text: "country" },
      %{ category: "music genre", text: "disco" },
      %{ category: "music genre", text: "dubstep" },
      %{ category: "music genre", text: "elevator music" },
      %{ category: "music genre", text: "grunge" },
      %{ category: "music genre", text: "heavy metal" },
      %{ category: "music genre", text: "hip hop" },
      %{ category: "music genre", text: "house" },
      %{ category: "music genre", text: "j-pop" },
      %{ category: "music genre", text: "jazz" },
      %{ category: "music genre", text: "pop" },
      %{ category: "music genre", text: "punk" },
      %{ category: "music genre", text: "r&b" },
      %{ category: "music genre", text: "rap" },
      %{ category: "music genre", text: "reggae" },
      %{ category: "music genre", text: "rock" },
      %{ category: "music genre", text: "swing" },
      %{ category: "music genre", text: "techno" },
      %{ category: "musical instrument", text: "accordion" },
      %{ category: "musical instrument", text: "bagpipes" },
      %{ category: "musical instrument", text: "banjo" },
      %{ category: "musical instrument", text: "bass guitar" },
      %{ category: "musical instrument", text: "bugle" },
      %{ category: "musical instrument", text: "castanets" },
      %{ category: "musical instrument", text: "cello" },
      %{ category: "musical instrument", text: "clarinet" },
      %{ category: "musical instrument", text: "cowbell" },
      %{ category: "musical instrument", text: "cymbal" },
      %{ category: "musical instrument", text: "didgeridoo" },
      %{ category: "musical instrument", text: "drums" },
      %{ category: "musical instrument", text: "electric guitar" },
      %{ category: "musical instrument", text: "fiddle" },
      %{ category: "musical instrument", text: "flute" },
      %{ category: "musical instrument", text: "gong" },
      %{ category: "musical instrument", text: "harmonica" },
      %{ category: "musical instrument", text: "harp" },
      %{ category: "musical instrument", text: "horn" },
      %{ category: "musical instrument", text: "jukebox" },
      %{ category: "musical instrument", text: "kazoo" },
      %{ category: "musical instrument", text: "lute" },
      %{ category: "musical instrument", text: "maraca" },
      %{ category: "musical instrument", text: "marimba" },
      %{ category: "musical instrument", text: "oboe" },
      %{ category: "musical instrument", text: "ocarina" },
      %{ category: "musical instrument", text: "piano" },
      %{ category: "musical instrument", text: "piccolo" },
      %{ category: "musical instrument", text: "saxophone" },
      %{ category: "musical instrument", text: "sitar" },
      %{ category: "musical instrument", text: "tambourine" },
      %{ category: "musical instrument", text: "triangle" },
      %{ category: "musical instrument", text: "trombone" },
      %{ category: "musical instrument", text: "trumpet" },
      %{ category: "musical instrument", text: "tuba" },
      %{ category: "musical instrument", text: "ukulele" },
      %{ category: "musical instrument", text: "violin" },
      %{ category: "musical instrument", text: "washboard" },
      %{ category: "musical instrument", text: "whistle" },
      %{ category: "musical instrument", text: "xylophone" },
      %{ category: "mythology", text: "amazon warrior" },
      %{ category: "mythology", text: "basilisk" },
      %{ category: "mythology", text: "bigfoot" },
      %{ category: "mythology", text: "centaur" },
      %{ category: "mythology", text: "chimera" },
      %{ category: "mythology", text: "cyclop" },
      %{ category: "mythology", text: "dragon" },
      %{ category: "mythology", text: "dryad" },
      %{ category: "mythology", text: "elf" },
      %{ category: "mythology", text: "fairy" },
      %{ category: "mythology", text: "genie" },
      %{ category: "mythology", text: "ghost" },
      %{ category: "mythology", text: "ghoul" },
      %{ category: "mythology", text: "giant" },
      %{ category: "mythology", text: "goblin" },
      %{ category: "mythology", text: "golem" },
      %{ category: "mythology", text: "griffin" },
      %{ category: "mythology", text: "imp" },
      %{ category: "mythology", text: "lizard people" },
      %{ category: "mythology", text: "magic carpet" },
      %{ category: "mythology", text: "manticore" },
      %{ category: "mythology", text: "medusa" },
      %{ category: "mythology", text: "mermaid" },
      %{ category: "mythology", text: "minotaur" },
      %{ category: "mythology", text: "minotaur" },
      %{ category: "mythology", text: "mummy" },
      %{ category: "mythology", text: "nymph" },
      %{ category: "mythology", text: "ogre" },
      %{ category: "mythology", text: "pegasus" },
      %{ category: "mythology", text: "phoenix" },
      %{ category: "mythology", text: "satyr" },
      %{ category: "mythology", text: "sphinx" },
      %{ category: "mythology", text: "troll" },
      %{ category: "mythology", text: "unicorn" },
      %{ category: "mythology", text: "vampire" },
      %{ category: "mythology", text: "werewolf" },
      %{ category: "mythology", text: "zombie" },
      %{ category: "plant", text: "avocado" },
      %{ category: "plant", text: "bamboo" },
      %{ category: "plant", text: "banana" },
      %{ category: "plant", text: "broccoli" },
      %{ category: "plant", text: "cabbage" },
      %{ category: "plant", text: "cactus" },
      %{ category: "plant", text: "carrot" },
      %{ category: "plant", text: "celery" },
      %{ category: "plant", text: "cherry" },
      %{ category: "plant", text: "cilantro" },
      %{ category: "plant", text: "coconut" },
      %{ category: "plant", text: "cucumber" },
      %{ category: "plant", text: "eggplant" },
      %{ category: "plant", text: "garlic" },
      %{ category: "plant", text: "grapes" },
      %{ category: "plant", text: "lemon" },
      %{ category: "plant", text: "lime" },
      %{ category: "plant", text: "mango" },
      %{ category: "plant", text: "oak" },
      %{ category: "plant", text: "orange" },
      %{ category: "plant", text: "palmtree" },
      %{ category: "plant", text: "peaches" },
      %{ category: "plant", text: "persimmon" },
      %{ category: "plant", text: "pineapple" },
      %{ category: "plant", text: "pinecone" },
      %{ category: "plant", text: "pinetree" },
      %{ category: "plant", text: "potato" },
      %{ category: "plant", text: "primrose" },
      %{ category: "plant", text: "seaweed" },
      %{ category: "plant", text: "spinach" },
      %{ category: "plant", text: "tomato" },
      %{ category: "plant", text: "watermelon" },
      %{ category: "plant", text: "wheat" },
      %{ category: "plant", text: "zucchini" },
      %{ category: "pop culture", text: "aladdin" },
      %{ category: "pop culture", text: "aquaman" },
      %{ category: "pop culture", text: "asterix" },
      %{ category: "pop culture", text: "autobots" },
      %{ category: "pop culture", text: "avatar" },
      %{ category: "pop culture", text: "barbie" },
      %{ category: "pop culture", text: "batman" },
      %{ category: "pop culture", text: "beavis" },
      %{ category: "pop culture", text: "bowser" },
      %{ category: "pop culture", text: "catwoman" },
      %{ category: "pop culture", text: "conan the barbarian" },
      %{ category: "pop culture", text: "garfield" },
      %{ category: "pop culture", text: "hawkeye" },
      %{ category: "pop culture", text: "iron chef" },
      %{ category: "pop culture", text: "kermit" },
      %{ category: "pop culture", text: "legend of zelda" },
      %{ category: "pop culture", text: "metroid" },
      %{ category: "pop culture", text: "mickey mouse" },
      %{ category: "pop culture", text: "pikachu" },
      %{ category: "pop culture", text: "rick & morty" },
      %{ category: "pop culture", text: "riddler" },
      %{ category: "pop culture", text: "rugrats" },
      %{ category: "pop culture", text: "scooby doo" },
      %{ category: "pop culture", text: "simba" },
      %{ category: "pop culture", text: "splinter" },
      %{ category: "pop culture", text: "spongebob" },
      %{ category: "pop culture", text: "superman" },
      %{ category: "pop culture", text: "the simpsons" },
      %{ category: "pop culture", text: "twoface" },
      %{ category: "pop culture", text: "voldemort" },
      %{ category: "profession", text: "artist" },
      %{ category: "profession", text: "assassin" },
      %{ category: "profession", text: "barber" },
      %{ category: "profession", text: "butcher" },
      %{ category: "profession", text: "captain" },
      %{ category: "profession", text: "cashier" },
      %{ category: "profession", text: "chef" },
      %{ category: "profession", text: "clown" },
      %{ category: "profession", text: "cook" },
      %{ category: "profession", text: "cowboy" },
      %{ category: "profession", text: "cowgirl" },
      %{ category: "profession", text: "dentist" },
      %{ category: "profession", text: "dj" },
      %{ category: "profession", text: "doctor" },
      %{ category: "profession", text: "drummer" },
      %{ category: "profession", text: "farmer" },
      %{ category: "profession", text: "firefighter" },
      %{ category: "profession", text: "gangster" },
      %{ category: "profession", text: "gardener" },
      %{ category: "profession", text: "gymnast" },
      %{ category: "profession", text: "hacker" },
      %{ category: "profession", text: "janitor" },
      %{ category: "profession", text: "lawyer" },
      %{ category: "profession", text: "magician" },
      %{ category: "profession", text: "mailman" },
      %{ category: "profession", text: "milkman" },
      %{ category: "profession", text: "movie director" },
      %{ category: "profession", text: "opera singer" },
      %{ category: "profession", text: "painter" },
      %{ category: "profession", text: "pilot" },
      %{ category: "profession", text: "plumber" },
      %{ category: "profession", text: "policeman" },
      %{ category: "profession", text: "poolboy" },
      %{ category: "profession", text: "priest" },
      %{ category: "profession", text: "princess" },
      %{ category: "profession", text: "sheriff" },
      %{ category: "profession", text: "soldier" },
      %{ category: "profession", text: "surgeon" },
      %{ category: "profession", text: "teacher" },
      %{ category: "profession", text: "teacher" },
      %{ category: "profession", text: "waiter" },
      %{ category: "profession", text: "warrior" },
      %{ category: "profession", text: "window cleaner " },
      %{ category: "profession", text: "wrestler" },
      %{ category: "snacks", text: "brownie" },
      %{ category: "snacks", text: "cookie" },
      %{ category: "snacks", text: "doritos" },
      %{ category: "snacks", text: "icecream" },
      %{ category: "snacks", text: "lollipop" },
      %{ category: "snacks", text: "popsicle" },
      %{ category: "snacks", text: "skittles" },
      %{ category: "snacks", text: "sour candy" },
      %{ category: "snacks", text: "sour candy" },
      %{ category: "snacks", text: "twinkie" },
      %{ category: "social", text: "bromance" },
      %{ category: "social", text: "divorce" },
      %{ category: "social", text: "follower" },
      %{ category: "social", text: "frenemy" },
      %{ category: "social", text: "highfive" },
      %{ category: "social", text: "marriage" },
      %{ category: "sports", text: "archery" },
      %{ category: "sports", text: "baseball" },
      %{ category: "sports", text: "basketball" },
      %{ category: "sports", text: "bowling" },
      %{ category: "sports", text: "boxing" },
      %{ category: "sports", text: "cricket" },
      %{ category: "sports", text: "curling" },
      %{ category: "sports", text: "dumbbell" },
      %{ category: "sports", text: "fencing" },
      %{ category: "sports", text: "fishing" },
      %{ category: "sports", text: "football" },
      %{ category: "sports", text: "frisbee" },
      %{ category: "sports", text: "goal post" },
      %{ category: "sports", text: "golf" },
      %{ category: "sports", text: "half pipe" },
      %{ category: "sports", text: "handball" },
      %{ category: "sports", text: "homerun" },
      %{ category: "sports", text: "iceskate" },
      %{ category: "sports", text: "javelin" },
      %{ category: "sports", text: "jumprope" },
      %{ category: "sports", text: "lacrosse" },
      %{ category: "sports", text: "longjump" },
      %{ category: "sports", text: "minigolf" },
      %{ category: "sports", text: "netball" },
      %{ category: "sports", text: "olympics" },
      %{ category: "sports", text: "pingpong" },
      %{ category: "sports", text: "rebound" },
      %{ category: "sports", text: "referee" },
      %{ category: "sports", text: "rock climbing" },
      %{ category: "sports", text: "slamdunk" },
      %{ category: "sports", text: "sledding" },
      %{ category: "sports", text: "soccer" },
      %{ category: "sports", text: "surfing" },
      %{ category: "sports", text: "swimming" },
      %{ category: "sports", text: "tennis" },
      %{ category: "sports", text: "volleyball" },
      %{ category: "toiletries", text: "hairdye" },
      %{ category: "toiletries", text: "hairgel" },
      %{ category: "toiletries", text: "lipstick" },
      %{ category: "toiletries", text: "mascara" },
      %{ category: "toiletries", text: "nailfile" },
      %{ category: "toiletries", text: "perfume" },
      %{ category: "toiletries", text: "shampoo" },
      %{ category: "toiletries", text: "sunblock" },
      %{ category: "tool", text: "chainsaw" },
      %{ category: "tool", text: "compass" },
      %{ category: "tool", text: "crowbar" },
      %{ category: "tool", text: "dustpan" },
      %{ category: "tool", text: "scissors" },
      %{ category: "tool", text: "stapler" },
      %{ category: "tool", text: "tweezers" },
      %{ category: "transportation", text: "airplane" },
      %{ category: "transportation", text: "bicycle" },
      %{ category: "transportation", text: "boat" },
      %{ category: "transportation", text: "bus" },
      %{ category: "transportation", text: "dog sled" },
      %{ category: "transportation", text: "double decker bus" },
      %{ category: "transportation", text: "f-16" },
      %{ category: "transportation", text: "forklift" },
      %{ category: "transportation", text: "formula one" },
      %{ category: "transportation", text: "golf cart" },
      %{ category: "transportation", text: "helicopter" },
      %{ category: "transportation", text: "hoverboard" },
      %{ category: "transportation", text: "ice cream truck" },
      %{ category: "transportation", text: "jeep" },
      %{ category: "transportation", text: "minivan" },
      %{ category: "transportation", text: "ocean liner" },
      %{ category: "transportation", text: "rickshaw" },
      %{ category: "transportation", text: "rocketship" },
      %{ category: "transportation", text: "rowboat" },
      %{ category: "transportation", text: "sail soat" },
      %{ category: "transportation", text: "scooter" },
      %{ category: "transportation", text: "shuttle" },
      %{ category: "transportation", text: "spaceship" },
      %{ category: "transportation", text: "sports car" },
      %{ category: "transportation", text: "stagecoach" },
      %{ category: "transportation", text: "steam boat" },
      %{ category: "transportation", text: "submarine" },
      %{ category: "transportation", text: "tow truck" },
      %{ category: "transportation", text: "tractor" },
      %{ category: "transportation", text: "train" },
      %{ category: "transportation", text: "tram" },
      %{ category: "transportation", text: "tricycle" },
      %{ category: "transportation", text: "tugboat" },
      %{ category: "transportation", text: "unicycle" },
      %{ category: "transportation", text: "yacht" },
      %{ category: "transportation", text: "zeppelin" },
      %{ category: "valuables", text: "bracelet" },
      %{ category: "valuables", text: "crystal" },
      %{ category: "valuables", text: "diamond" },
      %{ category: "valuables", text: "emerald" },
      %{ category: "valuables", text: "gold bar" },
      %{ category: "valuables", text: "jewelry" },
      %{ category: "valuables", text: "pearls" },
      %{ category: "weapon", text: "battle axe" },
      %{ category: "weapon", text: "bayonet" },
      %{ category: "weapon", text: "bazooka" },
      %{ category: "weapon", text: "cannon" },
      %{ category: "weapon", text: "catapult" },
      %{ category: "weapon", text: "crossbow" },
      %{ category: "weapon", text: "dynamite" },
      %{ category: "weapon", text: "handgun" },
      %{ category: "weapon", text: "missile" },
      %{ category: "weapon", text: "shotgun" },
      %{ category: "weapon", text: "sword" },
      %{ category: "weapon", text: "torpedo" },
      %{ category: "weapon", text: "warhammer" }
    ]
  end
  def artists do
    [
      "Pablo Picasso",
      "Vincent van Gogh",
      "Leonardo da Vinci",
      "Claude Monet",
      "Salvador Dalí",
      "Henri Matisse",
      "Rembrandt",
      "Andy Warhol",
      "Georgia O'Keeffe",
      "Michelangelo",
      "Peter Paul Rubens",
      "Edgar Degas",
      "Caravaggio",
      "Pierre-Auguste Renoir",
      "Raphael",
      "Paul Cezanne",
      "Joan Miro",
      "Jackson Pollock",
      "Wassily Kandinsky",
      "Rene Magritte",
      "Edward Hopper",
      "Frida Khalo",
      "Paul Gauguin"
    ]
  end
end
