name: Elixir CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:builder-latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:builder-latest
          cache-to: type=inline
          target: builder

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:builder-latest
            type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline

      - name: Deploy
        uses: darnfish/watchtower-update@v3.2
        with:
          url: https://portainer.ricardoramos.me/watchtower/v1/update
          api_token: "${{ secrets.WATCHTOWER_API_TOKEN }}"
          images: "ghcr.io/${{ github.repository }}"
